# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = mullvad-vpn
exec-once = discord --ozone-platform=x11
exec-once = python /usr/bin/streamdeck
exec-once = keepassxc
exec-once = WAYSCRIBER_TRAY_FORCE_PIXMAP=1 wayscriber --daemon

windowrule {
    name = discord_on_3
    workspace = 3
	monitor = 1
    match:class = ^discord$
}

windowrule {
    name = mullvad_on_10
    workspace = 10
	monitor = 2
    match:class = ^Mullvad VPN$
}

windowrule {
    name = streamdeck_on_10
    workspace = 10
	monitor = 2
    match:class = ^python3$
}

windowrule {
    name = keepass_on_10
    workspace = 10
	monitor = 2
    match:class = ^keepassxc$
}
