# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1


windowrule {
    name = transparent-terminal-kitty
    match:class = kitty
    opacity = 0.9 0.8
}

windowrule {
    name = transparent-terminal-ghostty
    match:class = com.mitchellh.ghostty
    opacity = 0.9 0.8
}

windowrule {
    name = transparent-discord
    match:class = discord
    opacity = 1 1
}

windowrule {
    name = transparent-vscode
    match:class = code-oss
    opacity = 0.9 0.8
}

windowrule {
    name = transparent-prism
    match:class = org.prismlauncher.PrismLauncher
    opacity = 0.9 0.8
}
